# Generated by Django 3.0.6 on 2020-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=80)),
                ('categories', models.TextField()),
                ('stat', models.CharField(choices=[('unresolved', 'unresolved'), ('assigned', 'assigned'), ('resolved', 'resolved')], max_length=20)),
            ],
        ),
    ]
