# Generated by Django 3.0.8 on 2020-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20200726_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('unresolved', 'unresolved'), ('assigned', 'assigned'), ('resolved', 'resolved')], max_length=20)),
                ('statText', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
