# Generated by Django 3.0.8 on 2020-07-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='complain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='complaints.Complaints'),
        ),
    ]
